import{VERSION,BUILD,PATHS,STORAGE,loadJson,safeGetObject,safeSetObject,safeGetString,safeGetArray,showToast,contrastRatio}from'./shared.js';
const DEFAULT={compact:false,reduceMotion:false};let prefs={...DEFAULT,...safeGetObject(STORAGE.preferences,DEFAULT)},settingsDialog,helpDialog,diagnosticsDialog;applyPrefs();document.addEventListener('DOMContentLoaded',init,{once:true});
function applyPrefs(){document.documentElement.dataset.density=prefs.compact?'compact':'comfortable';document.documentElement.dataset.reduceMotion=prefs.reduceMotion?'1':'0'}
function init(){const a=document.querySelector('.nav-actions');if(a){const v=document.createElement('span');v.className='version-chip';v.textContent=VERSION;v.title=`BUILD ${BUILD}`;a.prepend(v);const h=document.createElement('button');h.id='helpBtn';h.type='button';h.className='button button-quiet shell-icon-button';h.textContent='?';h.ariaLabel='ヘルプ';a.append(h);const s=document.createElement('button');s.id='settingsBtn';s.type='button';s.className='button button-quiet';s.textContent='設定';a.append(s)}
const f=document.createElement('footer');f.className='site-footer';f.innerHTML=`<div class="shell footer-inner"><div><strong>DesignShelf ${VERSION}</strong><span>BUILD ${BUILD}</span></div><p>GitHub Pages / APIキー不要 / 配色100件 / 画面骨格24件</p></div>`;document.body.append(f);
settingsDialog=dialog('settings','表示設定',`<div class="settings-list"><label class="setting-row"><span><strong>コンパクト表示</strong><small>候補を一度に見比べやすくします。</small></span><input id="compactModeToggle" type="checkbox"></label><label class="setting-row"><span><strong>動きを減らす</strong><small>画面内の動きを最小限にします。</small></span><input id="reduceMotionToggle" type="checkbox"></label></div><div class="settings-actions"><button class="button button-secondary" data-action="diagnostics">データ診断</button><button class="button button-secondary" data-action="reset">表示設定を初期化</button></div>`);
helpDialog=dialog('help','使い方・ショートカット',`<div class="help-grid"><section><h3>3ステップ</h3><ol class="help-steps"><li><strong>配色</strong><span>75 / 20 / 5の3色を選ぶ</span></li><li><strong>レイアウト</strong><span>画面骨格を選ぶ</span></li><li><strong>プロンプト</strong><span>作りたい内容を追加する</span></li></ol></section><section><h3>ショートカット</h3><div class="shortcut-list"><div><kbd>/</kbd><span>検索</span></div><div><kbd>R</kbd><span>ランダム提案</span></div><div><kbd>T</kbd><span>テーマ切替</span></div><div><kbd>?</kbd><span>ヘルプ</span></div><div><kbd>Esc</kbd><span>閉じる</span></div></div></section></div>`);
diagnosticsDialog=dialog('diagnostics','データ診断','<div id="diagnosticsBody"><p>診断を開始します。</p></div>');document.getElementById('settingsBtn')?.addEventListener('click',()=>{sync();settingsDialog.showModal()});document.getElementById('helpBtn')?.addEventListener('click',()=>helpDialog.showModal());settingsDialog.addEventListener('change',e=>{if(e.target.id==='compactModeToggle')prefs.compact=e.target.checked;if(e.target.id==='reduceMotionToggle')prefs.reduceMotion=e.target.checked;safeSetObject(STORAGE.preferences,prefs);applyPrefs()});settingsDialog.addEventListener('click',async e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='reset'){prefs={...DEFAULT};safeSetObject(STORAGE.preferences,prefs);applyPrefs();sync();showToast('表示設定を初期化しました')}if(action==='diagnostics'){settingsDialog.close();diagnosticsDialog.showModal();await diagnose()}});document.addEventListener('keydown',shortcuts)}
function dialog(id,title,body){const d=document.createElement('dialog');d.className='dialog shell-dialog';d.id=`designShelf-${id}`;d.innerHTML=`<div class="dialog-card shell-dialog-card"><button class="dialog-close" data-close aria-label="閉じる">×</button><p class="kicker">DESIGNSHELF</p><h2>${title}</h2>${body}</div>`;document.body.append(d);d.addEventListener('click',e=>{if(e.target===d||e.target.closest('[data-close]'))d.close()});return d}
function sync(){document.getElementById('compactModeToggle').checked=!!prefs.compact;document.getElementById('reduceMotionToggle').checked=!!prefs.reduceMotion}
function shortcuts(e){if(e.key==='Escape'){document.querySelectorAll('dialog[open]').forEach(d=>d.close());return}const tag=document.activeElement?.tagName||'';if(/INPUT|TEXTAREA|SELECT/.test(tag)||document.activeElement?.isContentEditable||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key==='/'){const q=document.querySelector('input[type="search"]');if(q){e.preventDefault();q.focus()}}if(e.key.toLowerCase()==='r'){const b=document.getElementById('randomPaletteBtn')||document.getElementById('randomLayoutBtn');if(b){e.preventDefault();b.click()}}if(e.key.toLowerCase()==='t')document.getElementById('themeToggleBtn')?.click();if(e.key==='?'){e.preventDefault();helpDialog.showModal()}}
async function diagnose(){const out=document.getElementById('diagnosticsBody');out.innerHTML='<p>診断中...</p>';try{const[p,l]=await Promise.all([loadJson(PATHS.palettes),loadJson(PATHS.layouts)]);const c=[];const add=(ok,label,detail)=>c.push({ok,label,detail});add(p.length===100,'配色データ',`${p.length}件 / 100件`);add(l.length===24,'レイアウト骨格',`${l.length}件 / 24件`);add(new Set(p.map(x=>x.id)).size===p.length,'配色ID','重複なし');add(new Set(l.map(x=>x.id)).size===l.length,'レイアウトID','重複なし');add(new Set(l.map(x=>x.wireframe)).size===l.length,'ワイヤーフレーム','水増しなし');const bad=p.filter(x=>!Object.values(x.colors||{}).every(v=>/^#[0-9a-f]{6}$/i.test(v)));add(!bad.length,'カラーコード',bad.length?`${bad.length}件異常`:'正常');let low=0;for(const x of p)for(const color of Object.values(x.colors))if(Math.max(contrastRatio(color,'#000000'),contrastRatio(color,'#ffffff'))<4.5)low++;add(!low,'文字コントラスト',low?`${low}色要確認`:'4.5:1以上');const pid=safeGetString(STORAGE.selectedPaletteId,''),lid=safeGetString(STORAGE.selectedLayoutId,'');add(!pid||p.some(x=>x.id===pid),'選択中配色',pid||'未選択');add(!lid||l.some(x=>x.id===lid),'選択中骨格',lid||'未選択');const failed=c.filter(x=>!x.ok).length;out.innerHTML=`<div class="diagnostic-summary ${failed?'has-warning':'is-ok'}"><strong>${failed?`${failed}件の要確認`:'問題は見つかりませんでした'}</strong><span>${VERSION} / ${BUILD}</span></div><div class="diagnostic-list">${c.map(x=>`<div class="diagnostic-row ${x.ok?'is-ok':'has-warning'}"><span class="diagnostic-icon">${x.ok?'✓':'!'}</span><div><strong>${x.label}</strong><small>${x.detail}</small></div></div>`).join('')}</div>`}catch(e){out.innerHTML=`<p>診断できませんでした: ${e.message}</p>`}}
